apiVersion: v1
kind: Secret
metadata:
  name: cloudvault-secret
type: Opaque
data:
  PORT: 
  MONGODB_URL: 
  MONGODB_TEST_URL: 
  FRONTEND_DEVELOPMENT_URL: 
  FRONTEND_PRODUCTION_URL: 
  JWT_SECRET: 
  REDIS_HOST: 
  REDIS_PASSWORD: 
  REDIS_USERNAME: 
  REDIS_PORT: 
  NODE_ENV:
